# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/nbdev_pub',
                'doc_host': 'https://GaoyangLiu.github.io',
                'git_url': 'https://github.com/GaoyangLiu/nbdev_pub',
                'lib_path': 'nbdev_pub'},
  'syms': {'nbdev_pub.core': {'nbdev_pub.core.foo': ('core.html#foo', 'nbdev_pub/core.py')}}}
